POST http://localhost:8080/events
content-type: application/json
authorization: asdkfnaksdklfnaklsndfkl;anskldnf;kanskdfn;asndknf;

{
    "name": "Titi",
    "description": "developer",
    "location": "berlin",
    "datetime": "{{$datetime iso8601}}"
}